import { useEffect, useState } from "react";
import { PremiumFooter, PremiumHeader } from "../../components/Shell";
import { clearSession, createAddress, deleteAddress, loadAccountDashboard, loadAddresses, type AccountOverview, type ApiAddress, type ApiUser, updateAccountProfile, updateAddress } from "../../lib/api";

const tabs = ["Overview", "Orders", "My routine", "Wishlist", "Addresses", "Profile"];
const emptyAddress = { label: "Home", full_name: "", phone: "", line1: "", line2: "", city: "", state: "", postal_code: "", country: "India", is_default: false };

export default function Account() {
  const [tab, setTab] = useState("Overview"); const [overview, setOverview] = useState<AccountOverview | null>(null); const [profile, setProfile] = useState<ApiUser | null>(null); const [addresses, setAddresses] = useState<ApiAddress[]>([]); const [address, setAddress] = useState<any>(emptyAddress); const [editing, setEditing] = useState<number | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([loadAccountDashboard(), loadAddresses()]).then(([data, saved]) => { setOverview(data); setProfile(data.profile); setAddresses(saved); }).catch(() => setError("Your session has expired. Please sign in again.")); }, []);
  const signOut = () => { clearSession(); window.location.href = "/login"; };
  const editAddress = (item?: ApiAddress) => { setEditing(item?.id ?? null); setAddress(item ? { ...item } : { ...emptyAddress }); };
  const saveAddress = async (event: React.FormEvent) => { event.preventDefault(); const payload = { label: address.label || "Home", full_name: address.full_name, phone: address.phone, line1: address.line1, line2: address.line2 || "", city: address.city, state: address.state, postal_code: address.postal_code, country: address.country || "India", is_default: Boolean(address.is_default) }; const saved = editing ? await updateAddress(editing, payload) : await createAddress(payload); setAddresses((old) => editing ? old.map((item) => item.id === saved.id ? saved : item) : [saved, ...old]); setEditing(null); setAddress(emptyAddress); setMessage("Address saved securely."); };
  if (error) return <main><PremiumHeader /><section className="empty-state account-guard"><h3>{error}</h3><a className="primary" href="/login?next=/account">Sign in →</a></section><PremiumFooter /></main>;
  if (!overview || !profile) return <main><PremiumHeader /><section className="empty-state account-guard"><h3>Opening your skin space.</h3><p>Fetching your routine and orders securely.</p></section><PremiumFooter /></main>;
  const renderTab = () => {
    if (tab === "Overview") return <><div className="profile-completion"><div><span>PROFILE COMPLETION</span><b>{profile.profile_completion_percent}%</b></div><i><u style={{ width: `${profile.profile_completion_percent}%` }} /></i><p>Complete your details for a smoother, more personal ritual.</p></div><div className="account-cards"><article className="next-order"><span>ACTIVE ORDER · {overview.active_order?.number ?? "NO ACTIVE ORDER"}</span><h3>{overview.active_order ? "Your ritual is on the move." : "Your next ritual starts here."}</h3><p>{overview.active_order ? `Expected delivery: ${overview.active_order.shipping_eta}` : "Explore the shelf and build a routine that feels good."}</p><a className="text-link" href="/shop">Explore formulas →</a></article><article className="routine-card"><span>YOUR AM ROUTINE</span><div>{overview.am_routine.map((product) => <img src={product.image} alt={product.name} key={product.slug} />)}</div><h3>Fresh · Treat · Protect</h3><a href="/shop">View routine →</a></article></div><h3 className="section-label">Recent orders</h3>{overview.recent_orders.map((order) => <div className="reorder" key={order.number}><div><span>{order.number} · {order.status}</span><h3>{order.item_count} products in your ritual</h3><p>₹{order.total} · {order.shipping_eta}</p></div></div>)}</>;
    if (tab === "Orders") return <div className="account-list">{overview.recent_orders.map((order) => <article className="account-order" key={order.number}><div><span>{order.number} · {order.status}</span><h3>{order.item_count} products · ₹{order.total}</h3><p>{order.shipping_eta}</p></div><b>{order.items.map((item) => item.product_name).join(", ")}</b></article>)}</div>;
    if (tab === "My routine" || tab === "Wishlist") { const products = tab === "My routine" ? overview.am_routine : overview.saved_products; return <div className="account-product-grid">{products.map((product) => <a className="account-product" href={`/products/${product.slug}`} key={product.slug}><img src={product.image} alt={product.name} /><span>{product.category}</span><h3>{product.name}</h3><b>₹{product.price}</b></a>)}</div>; }
    if (tab === "Addresses") return <div className="account-addresses"><div className="address-actions"><p>Save multiple delivery addresses for faster COD checkout.</p><button className="primary" onClick={() => editAddress()}>Add address +</button></div>{addresses.map((item) => <article className="account-detail-card" key={item.id}><div><span>{item.label.toUpperCase()} {item.is_default ? "· DEFAULT" : ""}</span><h3>{item.full_name}</h3><p>{item.line1}{item.line2 ? `, ${item.line2}` : ""}<br />{item.city}, {item.state} · {item.postal_code}<br />{item.phone}</p></div><div className="address-buttons"><button onClick={() => editAddress(item)}>Edit</button><button onClick={async () => { await deleteAddress(item.id); setAddresses((old) => old.filter((entry) => entry.id !== item.id)); }}>Delete</button></div></article>)}{(editing !== null || addresses.length === 0) && <form className="profile-form" onSubmit={saveAddress}><h3>{editing ? "Edit address" : "New address"}</h3><div className="two"><label className="field">Label<input value={address.label} onChange={(e) => setAddress({ ...address, label: e.target.value })} /></label><label className="field">Full name<input required value={address.full_name} onChange={(e) => setAddress({ ...address, full_name: e.target.value })} /></label></div><div className="two"><label className="field">Phone<input required value={address.phone} onChange={(e) => setAddress({ ...address, phone: e.target.value })} /></label><label className="field">Postal code<input required value={address.postal_code} onChange={(e) => setAddress({ ...address, postal_code: e.target.value })} /></label></div><label className="field">Address<input required value={address.line1} onChange={(e) => setAddress({ ...address, line1: e.target.value })} /></label><div className="two"><label className="field">City<input required value={address.city} onChange={(e) => setAddress({ ...address, city: e.target.value })} /></label><label className="field">State<input required value={address.state} onChange={(e) => setAddress({ ...address, state: e.target.value })} /></label></div><label className="check"><input type="checkbox" checked={address.is_default} onChange={(e) => setAddress({ ...address, is_default: e.target.checked })} /> Make default delivery address</label><button className="primary">Save address</button></form>}</div>;
    return <form className="profile-form" onSubmit={async (event) => { event.preventDefault(); const updated = await updateAccountProfile(profile); setProfile(updated); setOverview({ ...overview, profile: updated }); setMessage("Profile updated securely."); }}><div className="avatar-row">{profile.avatar_url ? <img src={profile.avatar_url} alt="Profile avatar" /> : <span>{profile.first_name[0]}</span>}<label className="field">Avatar image URL<input value={profile.avatar_url || ""} onChange={(e) => setProfile({ ...profile, avatar_url: e.target.value })} placeholder="https://..." /></label></div><div className="two"><label className="field">First name<input required value={profile.first_name} onChange={(e) => setProfile({ ...profile, first_name: e.target.value })} /></label><label className="field">Last name<input required value={profile.last_name} onChange={(e) => setProfile({ ...profile, last_name: e.target.value })} /></label></div><label className="field">Email<input required type="email" value={profile.email} onChange={(e) => setProfile({ ...profile, email: e.target.value })} /></label><div className="two"><label className="field">Phone<input value={profile.phone || ""} onChange={(e) => setProfile({ ...profile, phone: e.target.value })} /></label><label className="field">City<input value={profile.city || ""} onChange={(e) => setProfile({ ...profile, city: e.target.value })} /></label></div><label className="field">Skin type<input value={profile.skin_type || ""} onChange={(e) => setProfile({ ...profile, skin_type: e.target.value })} /></label><label className="field">Skin concerns<input value={profile.skin_concerns || ""} onChange={(e) => setProfile({ ...profile, skin_concerns: e.target.value })} /></label><button className="primary">Save profile</button></form>;
  };
  return <main><PremiumHeader /><section className="account-head"><div><p className="eyebrow">MY IN&ON</p><h1>Good morning,<br /><em>{profile.first_name} {profile.last_name.split(" ")[0]}</em></h1></div><div className="points"><span>GLOW POINTS</span><b>{profile.glow_points}</b><p>Your points are attached to this account.</p></div></section><section className="account-shell"><aside>{tabs.map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}<span>→</span></button>)}<button onClick={signOut}>Sign out</button></aside><div className="account-content"><p className="eyebrow red">{tab.toUpperCase()}</p><h2>{tab === "Overview" ? "Your skin space" : tab}</h2>{message && <p className="form-success">{message}</p>}{renderTab()}</div></section><PremiumFooter /></main>;
}
